name: user_list
description: User list project for Wajve Coding Challenge.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  http: ^0.13.4
  connectivity: ^3.0.6
  infinite_scroll_pagination: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true